### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by crilleengvall** [gazab/togglol#1]
Yo!

I'm using toggl as well and got interested in this repo. What does the description mean: 
"When you need to use Toggl a bit differently" what are the differences in togglol?

**Comment by gazab** [comment]
Haha, you're quick @crilleengvall! 

Togglol suits us who day after day just report 4 or 8 hour blocks to Toggl that in turn mainly are used to bill customers. Toggl SHOULD be used to get insights in every minute of a business to identify time sinks and ways to optimize. We don't use it like that unfortunately, but you probably do :)
Anyway, the site is live now so try it out yourself: https://www.togglol.com

Oh, and I will improve the readme someday..

**Comment by crilleengvall** [comment]
A ok, thanks! Nope, i don't use it that way either :)
