### ISSUE TITLE
Cant login

### ISSUE THREAD

**Issue by Heichichi** [gazab/togglol#24]
Error when clicking login:
0.togglol.dcc90226b37d2026145a.js:29 GET https://www.toggl.com/api/v8/me?with_related_data=true 403 ()
(anonymous) @ 0.togglol.dcc90226b37d2026145a.js:29
(anonymous) @ app.27f03e3221cf84c9613c.js:19
(anonymous) @ vendor.dc7aafb959437c362e76.js:11
value @ 0.togglol.dcc90226b37d2026145a.js:42
r @ app.27f03e3221cf84c9613c.js:1
a @ app.27f03e3221cf84c9613c.js:1
u @ app.27f03e3221cf84c9613c.js:1
f @ app.27f03e3221cf84c9613c.js:1
m @ app.27f03e3221cf84c9613c.js:1
n @ app.27f03e3221cf84c9613c.js:16
processEventQueue @ app.27f03e3221cf84c9613c.js:1
r @ app.27f03e3221cf84c9613c.js:18
handleTopLevel @ app.27f03e3221cf84c9613c.js:18
i @ app.27f03e3221cf84c9613c.js:18
perform @ app.27f03e3221cf84c9613c.js:1
batchedUpdates @ app.27f03e3221cf84c9613c.js:18
i @ app.27f03e3221cf84c9613c.js:1
dispatchEvent @ app.27f03e3221cf84c9613c.js:18
0.togglol.dcc90226b37d2026145a.js:29 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at 0.togglol.dcc90226b37d2026145a.js:29
    at <anonymous>

**Comment by gazab** [comment]
do you use both https and www?

**Comment by gazab** [comment]
The https&www redirect is propably broken. Will fix

**Comment by gazab** [comment]
Both https and redirect to www should now be in place.
