### ISSUE TITLE
Day summary shows NaNh when timer is running

### ISSUE THREAD

**Issue by Woblin** [gazab/togglol#28]
The daily summary shows NaNh when the timer is running in toggl.
![image](https://user-images.githubusercontent.com/196509/34098321-29af70da-e3dc-11e7-9401-fd1406d97972.png)

**Comment by justus-ragnarsson** [comment]
Toggl API returns `end: Invalid Date {}` for ongoing events which results in this error. Should Togglol discard these events, or use the current time in order to actually render something useful?

**Comment by gazab** [comment]
I just deployed a quick fix for this using the current date when end date is missing (i.e events for running timers).

But maybe it's time to figure out how timers should be included in Togglol. This tool was primarily for people who don't use timers at all but if it can be useful for everyone that's even better!

@Woblin how does your timer usage in Toggl look and how can Togglol improve it?
