### ISSUE TITLE
Show the faded red in the month view too

### ISSUE THREAD

**Issue by joshuadelange** [gazab/togglol#42]
I have been looking for a Toggl report like this one for a while! Thank you for making it.

I really like the red colour on the day heading as well. I would be great to show this colour on the month view too so you can see how busy your month has been.

**Comment by gazab** [comment]
That shouldn't be that hard to fix! I'll look into it in the coming days.

And I'm glad you like Togglol! :)

**Comment by gazab** [comment]
Fixed in #43 and deployed!
